<?php //These will be used when $config['mockuphappen_enable']==TRUE
$config['mockuphappen_request_array'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_install_app'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_install_page'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_user_id'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_user_facebook_id'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_facebook_page_id'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_page_id'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_log_user'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_authenticate'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_user_session'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_user'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_page_users'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_app_users'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_add_limit_service'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_count_limit_service'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_bar'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_get_started'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_setting_template'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_show_notification'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_read_notification'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_add_achievement_infos'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_login'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_facebook_tab_url'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_create_invite'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_accept_invite'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_invite_list'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_current_campaign'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_user_classes'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_add_campaign'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_page_role'] = array('status' => 'OK', 'success' => TRUE);
$config['mockuphappen_request_campaign_list'] = array('status' => 'OK', 'success' => TRUE);

$config['mockuphappen_facebook_page_id'] = '135287989899131';